name: Deploy-Pipeline

on:
  push:
    branches:
        - 'main'
    paths:
      - 'src/' # Changes in the File

  workflow_dispatch:

jobs:
    push_to_registry:
        name: Push Docker-Image to DockerHub
        runs-on: ubuntu-latest
        steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.MDMPYTHONPROJECT_REGISTRY_PASSWORD }}
    
        - name: Build and push Docker image
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: komendan/mdm-python-project:latest


    deploy_to_azure:
        name: Deploy Docker-Image to Azure
        needs: push_to_registry
        runs-on: ubuntu-latest
        permissions: 
          id-token: write #This is required for requesting the OIDC JWT Token
          contents: read #Required when GH token is used to authenticate with private repo
    
        steps:
          - name: Checkout to the branch
            uses: actions/checkout@v2
    
          - name: Azure Login
            uses: azure/login@v1
            with:
              client-id: ${{ secrets.MDMPYTHONPROJECT_AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.MDMPYTHONPROJECT_AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.MDMPYTHONPROJECT_AZURE_SUBSCRIPTION_ID }}
    
          - name: Deploy container app to AZURE
            uses: azure/container-apps-deploy-action@v2
            with:
              registryUrl: registry-1.docker.io
              registryUsername: ${{ secrets.MDMPYTHONPROJECT_REGISTRY_USERNAME }}
              registryPassword: ${{ secrets.MDMPYTHONPROJECT_REGISTRY_PASSWORD }}
              containerAppName: mdm-python-project
              resourceGroup: mdm-python-project
              imageToDeploy: docker.io/komendan/mdm-python-project:latest
              disableTelemetry: true
              environmentVariables: >-
                MONGODB_URI=secretref:mongodburi
                AZURE_STORAGE_CONNECTION_STRING=secretref:storage        